FROM golang:1.11.13

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
	curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - && \
	apt-get update -y && \
	apt-get install google-cloud-sdk google-cloud-sdk-app-engine-go google-cloud-sdk-app-engine-go google-cloud-sdk-datastore-emulator -y && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/uu64/line-bot-roomba
